workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    environment:
      flutter: 3.22.0
      xcode: latest
      cocoapods: default
    working_directory: FLUTTER/rotarehber_app
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
      - name: Build iOS IPA (no sign)
        script: |
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log

  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    environment:
      flutter: 3.22.0
    working_directory: FLUTTER/rotarehber_app
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
